### ISSUE TITLE
Project Level EXR Compression

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#103]
For DAN, we are running DWAA with 45% compression. It makes working VERY nice. But when we render, it runs out at uncompressed. Would be cool to have a project level setting (just like the colorspace in/out) that we can use to specify this and then have the write node pull from that.

**Comment by skeleturtle** [comment]
This has been added.

our write node will now look for the hubble setting 'exr_compression' if using DWAA or DWAB you can add a ';' to the value and provide the compression level, otherwise it will default to 45. if 'exr_compression' doesn't exist the write node will stick with the nuke default.

This has been merged to our jfx-nuke edge branch and is awaiting merge to main/release.
