### ISSUE TITLE
Hubble Instance Launch Issue

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#19]
When launching a new instance, if it's the first instance attempting to be launched it gets stuck waiting for way to long. The 2nd instance launched is able to connect after quicker.

**Comment by aldmbmtl** [comment]
The image pull policy on Kuiper is what is causing the workstation loading to take so long. My cluster is only connected over a 1g connection so if the image doesn't exist, it will just take that long to start up in hubble. Nothing we can do about that aside from get a faster network in my house.

- I pushed a change to Polaris Edge last night which meant it had to be pulled again with the update. You were just the first one awake so you got hit with the cache and it will take a long time the first time

- On AWS, it is very fast because they have 10g connections and the node can load it super quick. So in production, it is far better. Just my house is very slow because I can't afford a faster infra.
