### ISSUE TITLE
Juno File Renders

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#36]
**Is your feature request related to a problem? Please describe.**
When rendering out of Nuke, the resulting version is registered and set to "publish" and the status is set to "waiting_to_start". 

**Describe the solution you'd like**
When a render is initially sent out, it should have a state of "work" and a status of "in_progress". Once the artist confirms their frames, in Nuke they should be able to select the read node and say "Publish". That will then find the version in Luna and just change it's state to "publish" and the status to "pending_internal_review"

**Comment by oneBlueFish** [comment]
So currently the script that runs after a deadline renders the frames is "Creating Juno Publish for..." (which runs `/pipe/.../create_juno_entities.py`)
![image](https://github.com/juno-fx/report/assets/20176819/44513b83-fe86-4442-bb80-bb77a7f4ddf3)
The script runs `version.publish()`  on all the files returned by `version.files`, which works for Ingest, as we want to publish the plates once copied.
A diff script needs to run post exr renders (or we update the pipe script)
Instead of running `version.publish()`, the script can take the "dst_path" within  manifest file and run `version.create_juno_file()`

Because the script is running `version,publish()` on the versions' junofiles (which currently just resolves to the scene file), the version status is flipping to `Publish` on render, and leaving the status alone (could be changing the status, its late)

So what is currently happening is the following:
- Version up scene file (creates a version and a "scene" junofile) - sets the version to "work" and "waiting_to_start"
- Submit a writenode
- Exr's finish rendering, runs `create_juno_entities.py`
- Publishes junofiles (only scene) - flipping the state to "Publish"

I will make an update that creates a junofile on submission for the time being.  This will end up publishing both the scene file and the frames after render however.  We'll need to swap off / update `create_juno_entities.py`

**Comment by oneBlueFish** [comment]
![image](https://github.com/juno-fx/report/assets/20176819/80d2807a-f6df-40e8-ac6c-382788bb9733)

Just ran a test, positing image here as well

The one nice thing about creating the Exr Junofile before they finish rendering   -   You are able to load the images back in and watch / qc them in Nuke as they finish rendering

**Comment by skeleturtle** [comment]
I think creating the Juno file before hand is probably fine as you said. As for the code you should see in hubble config under strings something like juno_file_name I am using that for now.

**Comment by aldmbmtl** [comment]
This seems to be addressed and working now.
