### ISSUE TITLE
Alt + R JunoWrite

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#81]
![image](https://github.com/juno-fx/report/assets/9037579/1897d596-990b-4d78-9279-7f5565d008dd)

I get the following error when trying to create a read from write.

**Comment by skeleturtle** [comment]
I pushed up a branch for this bugfix. I didn't register the issue was with the hotkey command and not the command on the actual write node itself.

I wasn't able to actually test since my windows hotkeys kept interfering so if you are able to pull my branch down and confirm it's working that would be great

**Comment by skeleturtle** [comment]
correction I deleted the branch since edge is not up to date with our latest main. Before I delete the edge branch and create a new one can we confirm this wasn't intentional?

**Comment by skeleturtle** [comment]
This has been merged into edge

**Comment by aldmbmtl** [comment]
This actually works now! Pretty cool!
